### ISSUE TITLE
android7.0以下系统都会抛出这个异常,请指教谢谢

### ISSUE THREAD

**Issue by liujianying** [sundyCoder/hyperlpr4Android#3]
OpenCV Error: Unspecified error (FAILED: fs.is_open(). Can't open "/storage/emulated/0/pr/HorizonalFinemapping.prototxt") in bool cv::dnn::ReadProtoFromTextFile(const char*, google::protobuf::Message*), file /build/master_pack-android/opencv/modules/dnn/src/caffe/caffe_io.cpp, line 1113
12-19 12:55:25.604 1018-3306/? I/RenderThread: All controllers paused.

**Comment by sundyCoder** [comment]
从报错信息来看是 模型文件没有拷贝到系统里面，你检查下拷贝那部分的代码，android7.0以下的系统应该不一样。
