### ISSUE TITLE
项目编译报错如下，请教

### ISSUE THREAD

**Issue by zoze6** [sundyCoder/hyperlpr4Android#8]
——Error:error: '/SDK/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_highgui.a', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libhyperlpr.so', missing and no known rule to make it

**Comment by zoze6** [comment]
OpenCV路径多添加了一行注释有问题，已解决

**Comment by 0830arthur** [comment]
請問如何修正這問題??謝謝
